In [1]:
import os

import polars as pl

import plotly.express as px

from pytecgg import GNSSContext
from pytecgg.parsing import read_rinex_nav, read_rinex_obs
from pytecgg.utils import summarise_rinex_data, download_nav_bkg
from pytecgg.satellites import prepare_ephemeris, satellite_coordinates, calculate_ipp
from pytecgg.linear_combinations import calculate_linear_combinations
from pytecgg.tec_calibration import extract_arcs, calculate_tec, calculate_vertical_equivalent

OBS_NAV_DIR = 'data/calm-obs-nav'

In [2]:
def get_station_id(fid: str) -> str:
    for i, c in enumerate(fid):
        if c.isnumeric():
            return fid[:i]
    raise Exception("No station ID found")

file_ids = set([f[:-1] for f in os.listdir(OBS_NAV_DIR) if f.endswith('.25o') or f.endswith('.25n')])
obs_files = [f"{f}o" for f in file_ids]
nav_files = [f"{f}n" for f in file_ids]

In [7]:
f_idx = 0
nav_dict = read_rinex_nav(os.path.join(OBS_NAV_DIR, nav_files[f_idx]))
df_obs, rec_pos, rinex_version = read_rinex_obs(os.path.join(OBS_NAV_DIR, obs_files[f_idx]))
ctx = GNSSContext(
    receiver_pos=rec_pos,
    receiver_name=get_station_id(list(file_ids)[f_idx]),
    rinex_version=rinex_version,
    h_ipp=350_000,
    # systems=['G', 'E', 'R', 'C'],
    # systems=['G', 'E', 'R'],
    systems=['G', 'E'],
)
summarise_rinex_data(df_obs, nav_dict)

=======================================================
🛰️  GNSS RINEX DATA SUMMARY
=======================================================

📅 Temporal Coverage (OBS)

   - Start:    2025-11-28 00:00:00+00:00
   - End:      2025-11-28 23:59:45+00:00
   - Duration: 23:59:45
   - Sampling: 15.0s

📡 Constellations Breakdown (OBS)

Sys  | SVs  | Total Records   | Available Signals
-------------------------------------------------
E    | 26   | 409,089         | C1, C5, C7, C8, L1, L5, L7, L8, S1, S5, S7, S8
G    | 32   | 414,026         | C1, C2, C5, L1, L2, L5, P2, S1, S2, S5
R    | 24   | 248,234         | C1, C2, C7, L1, L2, L7, P1, S1, S2, S7
S    | 1    | 23,748          | C1, C5, L1, L5, S1, S5

📖 Ephemeris Coverage (NAV)

   - GPS     :  32 satellites have at least an ephemeris

In [8]:
df_obs

shape: (1_095_097, 4)
┌─────────────────────────┬─────┬────────────┬──────────┐
│ epoch                   ┆ sv  ┆ observable ┆ value    │
│ ---                     ┆ --- ┆ ---        ┆ ---      │
│ datetime[μs, UTC]       ┆ str ┆ str        ┆ f64      │
╞═════════════════════════╪═════╪════════════╪══════════╡
│ 2025-11-28 00:00:00 UTC ┆ G19 ┆ L1         ┆ 1.0718e8 │
│ 2025-11-28 00:00:00 UTC ┆ G19 ┆ L2         ┆ 8.3520e7 │
│ 2025-11-28 00:00:00 UTC ┆ G19 ┆ C1         ┆ 2.0396e7 │
│ 2025-11-28 00:00:00 UTC ┆ G19 ┆ P2         ┆ 2.0396e7 │
│ 2025-11-28 00:00:00 UTC ┆ G19 ┆ S1         ┆ 49.5     │
│ …                       ┆ …   ┆ …          ┆ …        │
│ 2025-11-28 23:59:45 UTC ┆ R09 ┆ C2         ┆ 2.3539e7 │
│ 2025-11-28 23:59:45 UTC ┆ R19 ┆ L1         ┆ 1.1496e8 │
│ 2025-11-28 23:59:45 UTC ┆ R19 ┆ L2         ┆ 8.9415e7 │
│ 2025-11-28 23:59:45 UTC ┆ R19 ┆ C1         ┆ 2.1491e7 │
│ 2025-11-28 23:59:45 UTC ┆ R19 ┆ P1         ┆ 2.1491e7 │
└─────────────────────────┴─────┴────────────┴──────────┘

In [9]:
ephem_dict = prepare_ephemeris(nav_dict, ctx=ctx)
ephem_dict

{'G02': {'constellation': 'GPS',
  'sv': 'G02',
  'datetime': datetime.datetime(2025, 11, 28, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 496800.0,
  'accuracy': 2.0,
  'cic': -3.557652235031e-07,
  'cis': -1.359730958939e-07,
  'clock_bias': -1.735985279083e-05,
  'clock_drift': 8.526512829121e-12,
  'clock_drift_rate': 0.0,
  'crc': 212.8125,
  'crs': -7.0625,
  'cuc': -3.501772880554e-07,
  'cus': 9.017065167427e-06,
  'deltaN': 4.294464595974e-09,
  'e': 0.0168668590486,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9639867186705,
  'idot': -7.214586230761e-11,
  'iodc': 93.0,
  'iode': 93.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -0.6709782757956,
  'omega': -0.889837087595,
  'omega0': -1.556433413185,
  'omegaDot': -8.166411592393e-09,
  'sqrta': 5153.629720688,
  't_tm': 489618.0,
  'tgd': -1.769512891769e-08,
  'toe': 496800.0},
 'G20': {'constellation': 'GPS',
  'sv': 'G20',
  'datetime': datetime.datetime(2025, 11, 28, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 460800.0,
  'accuracy': 2.0,
  'cic': 1.490116119385e-08,
  'cis': 6.146728992462e-08,
  'clock_bias': 0.000362167134881,
  'clock_drift': 0.0,
  'clock_drift_rate': 0.0,
  'crc': 263.09375,
  'crs': 23.15625,
  'cuc': 1.348555088043e-06,
  'cus': 6.001442670822e-06,
  'deltaN': 4.645193490954e-09,
  'e': 0.003673929837532,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9606579860954,
  'idot': 2.603679882289e-10,
  'iodc': 86.0,
  'iode': 86.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -1.80195603845,
  'omega': -2.11803538847,
  'omega0': -0.6058140397064,
  'omegaDot': -8.197484315269e-09,
  'sqrta': 5153.633283615,
  't_tm': 453618.0,
  'tgd': -8.381903171539e-09,
  'toe': 460800.0},
 'G30': {'constellation': 'GPS',
  'sv': 'G30',
  'datetime': datetime.datetime(2025, 11, 28, 20, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 504000.0,
  'accuracy': 2.0,
  'cic': 2.793967723846e-08,
  'cis': -1.136213541031e-07,
  'clock_bias': 3.880308941007e-05,
  'clock_drift': 1.182343112305e-11,
  'clock_drift_rate': 0.0,
  'crc': 173.40625,
  'crs': -45.65625,
  'cuc': -2.495944499969e-06,
  'cus': 1.01700425148e-05,
  'deltaN': 5.080568768939e-09,
  'e': 0.007729633129202,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9355720672919,
  'idot': 5.178787145843e-11,
  'iodc': 58.0,
  'iode': 58.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -2.891127397209,
  'omega': -2.353199093742,
  'omega0': 1.664066237187,
  'omegaDot': -8.111052143593e-09,
  'sqrta': 5153.584495544,
  't_tm': 496818.0,
  'tgd': 4.19095158577e-09,
  'toe': 504000.0},
 'G22': {'constellation': 'GPS',
  'sv': 'G22',
  'datetime': datetime.datetime(2025, 11, 28, 19, 59, 44, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 503984.0,
  'accuracy': 2.0,
  'cic': -1.117587089539e-07,
  'cis': -1.955777406693e-07,
  'clock_bias': -7.447367534041e-05,
  'clock_drift': 3.410605131648e-12,
  'clock_drift_rate': 0.0,
  'crc': 231.6875,
  'crs': 48.4375,
  'cuc': 2.447515726089e-06,
  'cus': 7.739290595055e-06,
  'deltaN': 4.90270421731e-09,
  'e': 0.0124654219253,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9583238710416,
  'idot': 2.014369620866e-10,
  'iodc': None,
  'iode': None,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': 0.5882412453747,
  'omega': -1.009823595,
  'omega0': 2.809605451916,
  'omegaDot': -8.39677833095e-09,
  'sqrta': 5153.634935379,
  't_tm': 503238.0,
  'tgd': -1.117587089539e-08,
  'toe': 503984.0},
 'G10': {'constellation': 'GPS',
  'sv': 'G10',
  'datetime': datetime.datetime(2025, 11, 28, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 475200.0,
  'accuracy': 2.0,
  'cic': 1.434236764908e-07,
  'cis': -9.313225746155e-09,
  'clock_bias': -0.000567386392504,
  'clock_drift': -4.661160346586e-12,
  'clock_drift_rate': 0.0,
  'crc': 278.25,
  'crs': 14.9375,
  'cuc': 6.444752216339e-07,
  'cus': 5.945563316345e-06,
  'deltaN': 3.886233305788e-09,
  'e': 0.0108729620697,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9919165487571,
  'idot': 3.875161416028e-10,
  'iodc': 97.0,
  'iode': 97.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -2.135524838896,
  'omega': -2.292043256116,
  'omega0': -0.4115541720032,
  'omegaDot': -7.761037564081e-09,
  'sqrta': 5153.650266647,
  't_tm': 468018.0,
  'tgd': 2.328306436539e-09,
  'toe': 475200.0},
 'G27': {'constellation': 'GPS',
  'sv': 'G27',
  'datetime': datetime.datetime(2025, 11, 28, 14, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 482400.0,
  'accuracy': 2.0,
  'cic': 2.793967723846e-08,
  'cis': -1.993030309677e-07,
  'clock_bias': -4.269508644938e-05,
  'clock_drift': -5.115907697473e-12,
  'clock_drift_rate': 0.0,
  'crc': 254.9375,
  'crs': 9.21875,
  'cuc': 4.302710294724e-07,
  'cus': 6.234273314476e-06,
  'deltaN': 4.660551273525e-09,
  'e': 0.01385934138671,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9542653837264,
  'idot': -2.060800126311e-10,
  'iodc': 9.0,
  'iode': 9.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -3.002548140365,
  'omega': 0.8568743438673,
  'omega0': -2.531042091834,
  'omegaDot': -8.063550164945e-09,
  'sqrta': 5153.659143448,
  't_tm': 475218.0,
  'tgd': 2.328306436539e-09,
  'toe': 482400.0},
 'G05': {'constellation': 'GPS',
  'sv': 'G05',
  'datetime': datetime.datetime(2025, 11, 28, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 460800.0,
  'accuracy': 2.0,
  'cic': -2.235174179077e-08,
  'cis': 5.215406417847e-08,
  'clock_bias': -0.0002244859933853,
  'clock_drift': -6.821210263297e-13,
  'clock_drift_rate': 0.0,
  'crc': 274.875,
  'crs': 17.4375,
  'cuc': 1.102685928345e-06,
  'cus': 5.984678864479e-06,
  'deltaN': 4.321965741507e-09,
  'e': 0.005457903142087,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9789568500765,
  'idot': 1.721500278825e-10,
  'iodc': 66.0,
  'iode': 66.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': 0.3611262505864,
  'omega': 1.438304289478,
  'omega0': -0.4674239760505,
  'omegaDot': -8.188555371914e-09,
  'sqrta': 5153.653299332,
  't_tm': 453618.0,
  'tgd': -1.071020960808e-08,
  'toe': 460800.0},
 'G12': {'constellation': 'GPS',
  'sv': 'G12',
  'datetime': datetime.datetime(2025, 11, 28, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 453600.0,
  'accuracy': 2.0,
  'cic': 1.043081283569e-07,
  'cis': -1.899898052216e-07,
  'clock_bias': -0.000604284927249,
  'clock_drift': -6.821210263297e-13,
  'clock_drift_rate': 0.0,
  'crc': 235.65625,
  'crs': 38.625,
  'cuc': 1.886859536171e-06,
  'cus': 7.340684533119e-06,
  'deltaN': 4.638407494005e-09,
  'e': 0.008966397610493,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9596970902988,
  'idot': 2.010798043524e-10,
  'iodc': 34.0,
  'iode': 34.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': 1.771684530023,
  'omega': 1.525147409106,
  'omega0': 2.789570902928,
  'omegaDot': -8.091051310478e-09,
  'sqrta': 5153.591508865,
  't_tm': 446418.0,
  'tgd': -1.257285475731e-08,
  'toe': 453600.0},
 'G04': {'constellation': 'GPS',
  'sv': 'G04',
  'datetime': datetime.datetime(2025, 11, 28, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 496800.0,
  'accuracy': 2.0,
  'cic': 6.891787052155e-08,
  'cis': -7.82310962677e-08,
  'clock_bias': 2.765050157905e-05,
  'clock_drift': 2.84217094304e-12,
  'clock_drift_rate': 0.0,
  'crc': 278.3125,
  'crs': -56.5625,
  'cuc': -3.080815076828e-06,
  'cus': 5.340203642845e-06,
  'deltaN': 4.500544608605e-09,
  'e': 0.003674957086332,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9696728120677,
  'idot': 7.500312418118e-11,
  'iodc': 356.0,
  'iode': 100.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -1.192326491881,
  'omega': -2.952496923279,
  'omega0': 0.6621936575381,
  'omegaDot': -8.139624762329e-09,
  'sqrta': 5153.760425568,
  't_tm': 489618.0,
  'tgd': -4.656612873077e-09,
  'toe': 496800.0},
 'G29': {'constellation': 'GPS',
  'sv': 'G29',
  'datetime': datetime.datetime(2025, 11, 28, 7, 59, 44, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 460784.0,
  'accuracy': 2.0,
  'cic': 2.98023223877e-08,
  'cis': 5.587935447693e-09,
  'clock_bias': -0.0004184367135167,
  'clock_drift': 6.025402399246e-12,
  'clock_drift_rate': 0.0,
  'crc': 247.3125,
  'crs': 11.40625,
  'cuc': 5.792826414108e-07,
  'cus': 6.813555955887e-06,
  'deltaN': 4.546260798582e-09,
  'e': 0.003290560329333,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9634732783122,
  'idot': -1.950081228711e-10,
  'iodc': 24.0,
  'iode': 24.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -0.01859334792757,
  'omega': 2.776738050948,
  'omega0': -2.442381271623,
  'omegaDot': -8.172840431609e-09,
  'sqrta': 5153.561149597,
  't_tm': 459606.0,
  'tgd': -9.778887033463e-09,
  'toe': 460784.0},
 'G26': {'constellation': 'GPS',
  'sv': 'G26',
  'datetime': datetime.datetime(2025, 11, 28, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 489600.0,
  'accuracy': 2.0,
  'cic': 1.303851604462e-08,
  'cis': 1.061707735062e-07,
  'clock_bias': -0.0002864310517907,
  'clock_drift': -5.570655048359e-12,
  'clock_drift_rate': 0.0,
  'crc': 203.0625,
  'crs': 42.5625,
  'cuc': 2.309679985046e-06,
  'cus': 8.117407560349e-06,
  'deltaN': 5.501300579822e-09,
  'e': 0.01078763057012,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9286426442079,
  'idot': 6.714565402886e-11,
  'iodc': 96.0,
  'iode': 96.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -0.1978300344264,
  'omega': 0.6825069918986,
  'omega0': 2.623822385488,
  'omegaDot': -8.647145902621e-09,
  'sqrta': 5153.666921616,
  't_tm': 482418.0,
  'tgd': 6.519258022308e-09,
  'toe': 489600.0},
 'G01': {'constellation': 'GPS',
  'sv': 'G01',
  'datetime': datetime.datetime(2025, 11, 28, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 489600.0,
  'accuracy': 2.0,
  'cic': 9.313225746155e-09,
  'cis': 9.313225746155e-09,
  'clock_bias': 0.0003535482101142,
  'clock_drift': -1.023181539495e-12,
  'clock_drift_rate': 0.0,
  'crc': 219.84375,
  'crs': 14.8125,
  'cuc': 8.717179298401e-07,
  'cus': 8.249655365944e-06,
  'deltaN': 4.308750905342e-09,
  'e': 0.001098414533772,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9584180888175,
  'idot': -3.178703834345e-11,
  'iodc': 566.0,
  'iode': 54.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -3.068779630784,
  'omega': -0.09389503430506,
  'omega0': -1.393306459572,
  'omegaDot': -8.075336370173e-09,
  'sqrta': 5153.647035599,
  't_tm': 482418.0,
  'tgd': -8.847564458847e-09,
  'toe': 489600.0},
 'G13': {'constellation': 'GPS',
  'sv': 'G13',
  'datetime': datetime.datetime(2025, 11, 28, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 460800.0,
  'accuracy': 2.0,
  'cic': -6.332993507385e-08,
  'cis': 8.195638656616e-08,
  'clock_bias': 0.0006932658143342,
  'clock_drift': -6.821210263297e-13,
  'clock_drift_rate': 0.0,
  'crc': 255.78125,
  'crs': -62.46875,
  'cuc': -3.216788172722e-06,
  'cus': 6.701797246933e-06,
  'deltaN': 4.389111395536e-09,
  'e': 0.009842526400462,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.975346937332,
  'idot': -1.646497154644e-10,
  'iodc': 133.0,
  'iode': 133.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -0.2453495342615,
  'omega': 1.008869375962,
  'omega0': 0.7727176158189,
  'omegaDot': -8.220342410257e-09,
  'sqrta': 5153.676567078,
  't_tm': 453618.0,
  'tgd': -1.117587089539e-08,
  'toe': 460800.0},
 'G03': {'constellation': 'GPS',
  'sv': 'G03',
  'datetime': datetime.datetime(2025, 11, 28, 15, 59, 44, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 489584.0,
  'accuracy': 2.0,
  'cic': -8.568167686462e-08,
  'cis': 5.774199962616e-08,
  'clock_bias': 0.0006353263743222,
  'clock_drift': -8.071765478235e-12,
  'clock_drift_rate': 0.0,
  'crc': 270.78125,
  'crs': 16.09375,
  'cuc': 7.171183824539e-07,
  'cus': 6.403774023056e-06,
  'deltaN': 3.821230598164e-09,
  'e': 0.006313462741673,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9923644328305,
  'idot': 2.650110387735e-10,
  'iodc': 68.0,
  'iode': 68.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': 0.8952459214432,
  'omega': 1.225133749361,
  'omega0': -0.4091607795088,
  'omegaDot': -7.974260731396e-09,
  'sqrta': 5153.677804947,
  't_tm': 482418.0,
  'tgd': 1.396983861923e-09,
  'toe': 489584.0},
 'G24': {'constellation': 'GPS',
  'sv': 'G24',
  'datetime': datetime.datetime(2025, 11, 28, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 453600.0,
  'accuracy': 2.0,
  'cic': 1.6950070858e-07,
  'cis': -1.285225152969e-07,
  'clock_bias': -0.0002216305583715,
  'clock_drift': 1.364242052659e-11,
  'clock_drift_rate': 0.0,
  'crc': 153.21875,
  'crs': -40.8125,
  'cuc': -2.123415470123e-06,
  'cus': 1.074001193047e-05,
  'deltaN': 4.781984903151e-09,
  'e': 0.01773967884947,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9342845501645,
  'idot': 7.571743964957e-11,
  'iodc': 9.0,
  'iode': 9.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -2.887908569281,
  'omega': 1.11982842656,
  'omega0': 1.565244094791,
  'omegaDot': -7.89711466081e-09,
  'sqrta': 5153.665189743,
  't_tm': 446418.0,
  'tgd': 2.328306436539e-09,
  'toe': 453600.0},
 'G31': {'constellation': 'GPS',
  'sv': 'G31',
  'datetime': datetime.datetime(2025, 11, 28, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 489600.0,
  'accuracy': 2.0,
  'cic': -1.005828380585e-07,
  'cis': 1.341104507446e-07,
  'clock_bias': -0.0001806486397982,
  'clock_drift': 1.932676241267e-12,
  'clock_drift_rate': 0.0,
  'crc': 186.53125,
  'crs': -37.03125,
  'cuc': -1.678243279457e-06,
  'cus': 9.924173355103e-06,
  'deltaN': 4.79127100424e-09,
  'e': 0.01091632130556,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9541363602035,
  'idot': -8.357490980188e-11,
  'iodc': 179.0,
  'iode': 179.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': 0.3603755673403,
  'omega': 0.914960569746,
  'omega0': 1.695622923535,
  'omegaDot': -8.199627261674e-09,
  'sqrta': 5153.745914459,
  't_tm': 482418.0,
  'tgd': -1.350417733192e-08,
  'toe': 489600.0},
 'G08': {'constellation': 'GPS',
  'sv': 'G08',
  'datetime': datetime.datetime(2025, 11, 28, 20, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 504000.0,
  'accuracy': 2.0,
  'cic': 9.499490261078e-08,
  'cis': 1.285225152969e-07,
  'clock_bias': 0.0005190107040107,
  'clock_drift': -2.955857780762e-12,
  'clock_drift_rate': 0.0,
  'crc': 270.5625,
  'crs': 11.8125,
  'cuc': 6.575137376785e-07,
  'cus': 5.008652806282e-06,
  'deltaN': 5.296292040394e-09,
  'e': 0.0111028138781,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9451763687896,
  'idot': -3.239420649158e-10,
  'iodc': 79.0,
  'iode': 79.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': 0.06781507290713,
  'omega': 0.4796842843187,
  'omega0': -2.562433333851,
  'omegaDot': -8.707505559701e-09,
  'sqrta': 5153.642656326,
  't_tm': 496818.0,
  'tgd': 4.656612873077e-09,
  'toe': 504000.0},
 'G19': {'constellation': 'GPS',
  'sv': 'G19',
  'datetime': datetime.datetime(2025, 11, 28, 3, 59, 44, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 446384.0,
  'accuracy': 2.0,
  'cic': 1.303851604462e-07,
  'cis': -6.519258022308e-08,
  'clock_bias': 0.0006774463690817,
  'clock_drift': 2.160049916711e-12,
  'clock_drift_rate': 0.0,
  'crc': 241.75,
  'crs': 11.03125,
  'cuc': 5.532056093216e-07,
  'cus': 7.139518857002e-06,
  'deltaN': 4.788413742367e-09,
  'e': 0.01085999526549,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.960034098348,
  'idot': -2.146517982518e-10,
  'iodc': 36.0,
  'iode': 36.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -0.2896482736532,
  'omega': 2.89967864346,
  'omega0': -2.414760961355,
  'omegaDot': -8.296774165375e-09,
  'sqrta': 5153.691133499,
  't_tm': 439218.0,
  'tgd': -1.536682248116e-08,
  'toe': 446384.0},
 'G11': {'constellation': 'GPS',
  'sv': 'G11',
  'datetime': datetime.datetime(2025, 11, 28, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 453600.0,
  'accuracy': 2.0,
  'cic': 4.470348358154e-08,
  'cis': 2.235174179077e-08,
  'clock_bias': -0.000529479701072,
  'clock_drift': 1.364242052659e-11,
  'clock_drift_rate': 0.0,
  'crc': 223.65625,
  'crs': 33.03125,
  'cuc': 1.788139343262e-06,
  'cus': 8.219853043556e-06,
  'deltaN': 4.439113478323e-09,
  'e': 0.002286950941198,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9642386317008,
  'idot': -1.178620522847e-11,
  'iodc': 653.0,
  'iode': 141.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -1.929719070191,
  'omega': -2.27923759832,
  'omega0': -1.424295443005,
  'omegaDot': -8.019262605905e-09,
  'sqrta': 5153.756664276,
  't_tm': 446418.0,
  'tgd': -8.847564458847e-09,
  'toe': 453600.0},
 'G23': {'constellation': 'GPS',
  'sv': 'G23',
  'datetime': datetime.datetime(2025, 11, 28, 11, 44, 32, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 474272.0,
  'accuracy': 2.0,
  'cic': 6.146728992462e-08,
  'cis': -1.303851604462e-08,
  'clock_bias': 0.0005783643573523,
  'clock_drift': 5.343281372916e-12,
  'clock_drift_rate': 0.0,
  'crc': 273.90625,
  'crs': 15.125,
  'cuc': 8.363276720047e-07,
  'cus': 6.094574928284e-06,
  'deltaN': 4.01409577463e-09,
  'e': 0.00594005768653,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9869258359139,
  'idot': 3.267993267894e-10,
  'iodc': 371.0,
  'iode': 115.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -1.148976874722,
  'omega': -2.780119543664,
  'omega0': -0.4431758660423,
  'omegaDot': -7.924615806343e-09,
  'sqrta': 5153.692211151,
  't_tm': 467118.0,
  'tgd': -8.381903171539e-09,
  'toe': 474272.0},
 'G06': {'constellation': 'GPS',
  'sv': 'G06',
  'datetime': datetime.datetime(2025, 11, 28, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 453600.0,
  'accuracy': 2.0,
  'cic': -4.097819328308e-08,
  'cis': 5.774199962616e-08,
  'clock_bias': -0.0005803252570331,
  'clock_drift': -6.821210263297e-12,
  'clock_drift_rate': 0.0,
  'crc': 232.1875,
  'crs': 25.75,
  'cuc': 1.460313796997e-06,
  'cus': 8.409842848778e-06,
  'deltaN': 3.89409077594e-09,
  'e': 0.003718386287801,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9873936010439,
  'idot': -1.85722021782e-11,
  'iodc': 30.0,
  'iode': 30.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -2.888885472327,
  'omega': -0.6898936529541,
  'omega0': -1.445175868781,
  'omegaDot': -7.706392430749e-09,
  'sqrta': 5153.693576813,
  't_tm': 446418.0,
  'tgd': 3.725290298462e-09,
  'toe': 453600.0},
 'G32': {'constellation': 'GPS',
  'sv': 'G32',
  'datetime': datetime.datetime(2025, 11, 28, 14, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 482400.0,
  'accuracy': 2.0,
  'cic': 1.601874828339e-07,
  'cis': -2.421438694e-08,
  'clock_bias': -0.0002298871986568,
  'clock_drift': 1.568878360558e-11,
  'clock_drift_rate': 0.0,
  'crc': 276.71875,
  'crs': -63.3125,
  'cuc': -3.24472784996e-06,
  'cus': 5.371868610382e-06,
  'deltaN': 4.6091205598e-09,
  'e': 0.008934413548559,
  'fitInt': 4.0,
  'health': 0.0,
  'i0': 0.9668902833642,
  'idot': 9.178953768839e-11,
  'iodc': 44.0,
  'iode': 44.0,
  'l2Codes': 1.0,
  'l2p': 0.0,
  'm0': -2.361642268383,
  'omega': -2.051317572879,
  'omega0': 0.6154207754998,
  'omegaDot': -8.064621638148e-09,
  'sqrta': 5153.691167831,
  't_tm': 475218.0,
  'tgd': 9.313225746155e-10,
  'toe': 482400.0},
 'G17': {'constellation': 'GPS',
  'sv': 'G17',
  'datetime': datetime.datetime(2025, 11, 28, 4, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')),
  'gps_week': 2394,
  'gps_seconds': 446400.0,
  'accuracy': 2.8,
  'cic': 1.303851604462e-08,
  'cis': 3.017485141754e-07,
  'clock_bias': 1.792795956135e-05,
  'clock_drift': -1.284661266254e-11,
  'clock_drift_rate': 0.0,
  'crc': 241.5625,
  'crs': 15.53125,
  'cuc': 1.076608896255e-06,
  'cus': 7.109716534615e-06,
  'deltaN': 4.639121809473e-09,
  'e': 0.01310197252315,
  'fitInt': 4.0,

In [10]:
# Compute selected linear combinations
df_lc = calculate_linear_combinations(
    df_obs,
    ctx=ctx,
    combinations=["gflc_phase", "gflc_code", "mw"],
    selection_mode="quality",
    # band_overrides={"G": ("L1", "L2")},
    # band_overrides={"G": ("L1", "L2"), "S": ("L1", "L5")}
)

df_lc

shape: (82_792, 5)
┌─────────────────────────┬─────┬─────────────┬────────────┬────────────┐
│ epoch                   ┆ sv  ┆ gflc_phase  ┆ gflc_code  ┆ mw         │
│ ---                     ┆ --- ┆ ---         ┆ ---        ┆ ---        │
│ datetime[μs, UTC]       ┆ str ┆ f64         ┆ f64        ┆ f64        │
╞═════════════════════════╪═════╪═════════════╪════════════╪════════════╡
│ 2025-11-28 00:00:00 UTC ┆ G19 ┆ -238.459119 ┆ 63.654738  ┆ -23.56864  │
│ 2025-11-28 00:00:00 UTC ┆ G01 ┆ -120.327384 ┆ 103.286665 ┆ -14.951112 │
│ 2025-11-28 00:00:00 UTC ┆ G13 ┆ -153.094106 ┆ 89.485922  ┆ -49.284904 │
│ 2025-11-28 00:00:00 UTC ┆ G17 ┆ -236.224711 ┆ 75.066525  ┆ 6.856725   │
│ 2025-11-28 00:00:00 UTC ┆ G22 ┆ -173.034919 ┆ 76.475153  ┆ -24.895292 │
│ …                       ┆ …   ┆ …           ┆ …          ┆ …          │
│ 2025-11-28 23:59:30 UTC ┆ E02 ┆ -199.732747 ┆ 62.640294  ┆ -56.778496 │
│ 2025-11-28 23:59:30 UTC ┆ E27 ┆ -207.027554 ┆ 56.547031  ┆ -58.996317 │
│ 2025-11-28 23:59:30 UTC ┆ E07 ┆ -156.208125 ┆ 66.645547  ┆ -42.201514 │
│ 2025-11-28 23:59:30 UTC ┆ E08 ┆ -61.879511  ┆ 74.951014  ┆ -27.578713 │
│ 2025-11-28 23:59:30 UTC ┆ E30 ┆ -220.762606 ┆ 46.751238  ┆ -58.50399  │
└─────────────────────────┴─────┴─────────────┴────────────┴────────────┘

In [13]:
# Identify continuous arcs, detect cycle slips
# and loss-of-lock events
df_arcs = extract_arcs(
    df=df_lc,
    ctx=ctx,
    threshold_abs=10,
    threshold_std=10,
    threshold_jump=5
)

df_arcs

shape: (82_792, 13)
┌────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ epoch      ┆ sv  ┆ gflc_phase ┆ gflc_code  ┆ … ┆ gflc_phase ┆ gflc_code_ ┆ mw_fix    ┆ gflc_leve │
│ ---        ┆ --- ┆ ---        ┆ ---        ┆   ┆ _fix       ┆ fix        ┆ ---       ┆ lled      │
│ datetime[μ ┆ str ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ f64       ┆ ---       │
│ s, UTC]    ┆     ┆            ┆            ┆   ┆ f64        ┆ f64        ┆           ┆ f64       │
╞════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2025-11-28 ┆ G19 ┆ -238.45911 ┆ 63.654738  ┆ … ┆ -238.45911 ┆ 63.654738  ┆ -23.56864 ┆ 55.671883 │
│ 00:00:00   ┆     ┆ 9          ┆            ┆   ┆ 9          ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G01 ┆ -120.32738 ┆ 103.286665 ┆ … ┆ -120.32738 ┆ 103.286665 ┆ -14.95111 ┆ 103.44157 │
│ 00:00:00   ┆     ┆ 4          ┆            ┆   ┆ 4          ┆            ┆ 2         ┆ 9         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G13 ┆ -153.09410 ┆ 89.485922  ┆ … ┆ -153.09410 ┆ 89.485922  ┆ -49.28490 ┆ 71.7088   │
│ 00:00:00   ┆     ┆ 6          ┆            ┆   ┆ 6          ┆            ┆ 4         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G17 ┆ -236.22471 ┆ 75.066525  ┆ … ┆ -236.22471 ┆ 75.066525  ┆ 6.856725  ┆ 90.875799 │
│ 00:00:00   ┆     ┆ 1          ┆            ┆   ┆ 1          ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G22 ┆ -173.03491 ┆ 76.475153  ┆ … ┆ -173.03491 ┆ 76.475153  ┆ -24.89529 ┆ 104.26918 │
│ 00:00:00   ┆     ┆ 9          ┆            ┆   ┆ 9          ┆            ┆ 2         ┆ 5         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2025-11-28 ┆ E02 ┆ -199.73274 ┆ 62.640294  ┆ … ┆ -199.73274 ┆ 53.72162   ┆ -56.77849 ┆ 60.979762 │
│ 23:59:30   ┆     ┆ 7          ┆            ┆   ┆ 7          ┆            ┆ 6         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E27 ┆ -207.02755 ┆ 56.547031  ┆ … ┆ -207.02755 ┆ 56.112353  ┆ -58.99631 ┆ 52.090205 │
│ 23:59:30   ┆     ┆ 4          ┆            ┆   ┆ 4          ┆            ┆ 7         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E07 ┆ -156.20812 ┆ 66.645547  ┆ … ┆ -156.20812 ┆ 60.948152  ┆ -42.20151 ┆ 64.003821 │
│ 23:59:30   ┆     ┆ 5          ┆            ┆   ┆ 5          ┆            ┆ 4         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E08 ┆ -61.879511 ┆ 74.951014  ┆ … ┆ -61.879511 ┆ 78.226627  ┆ -27.57871 ┆ 78.649512 │
│ 23:59:30   ┆     ┆            ┆            ┆   ┆            ┆            ┆ 3         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E30 ┆ -220.76260 ┆ 46.751238  ┆ … ┆ -220.76260 ┆ 46.751238  ┆ -58.50399 ┆ 51.000133 │
│ 23:59:30   ┆     ┆ 6          ┆            ┆   ┆ 6          ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [14]:
df_arcs.filter(
    pl.col('is_loss_of_lock')
)

shape: (1_247, 13)
┌────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ epoch      ┆ sv  ┆ gflc_phase ┆ gflc_code  ┆ … ┆ gflc_phase ┆ gflc_code_ ┆ mw_fix    ┆ gflc_leve │
│ ---        ┆ --- ┆ ---        ┆ ---        ┆   ┆ _fix       ┆ fix        ┆ ---       ┆ lled      │
│ datetime[μ ┆ str ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ f64       ┆ ---       │
│ s, UTC]    ┆     ┆            ┆            ┆   ┆ f64        ┆ f64        ┆           ┆ f64       │
╞════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2025-11-28 ┆ G11 ┆ null       ┆ null       ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 00:15:15   ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G11 ┆ null       ┆ null       ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 00:15:30   ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G11 ┆ null       ┆ null       ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 00:15:45   ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G11 ┆ null       ┆ null       ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 00:16:00   ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G11 ┆ null       ┆ null       ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 00:16:15   ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2025-11-28 ┆ E07 ┆ -148.17152 ┆ 77.473702  ┆ … ┆ -148.17152 ┆ 77.473702  ┆ -42.23697 ┆ 72.040418 │
│ 21:48:15   ┆     ┆ 7          ┆            ┆   ┆ 7          ┆            ┆ 7         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E08 ┆ -87.590191 ┆ 54.909224  ┆ … ┆ -87.590191 ┆ 54.909224  ┆ -27.87052 ┆ 52.938832 │
│ 21:48:15   ┆     ┆            ┆            ┆   ┆            ┆            ┆ 1         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E30 ┆ -207.05060 ┆ 62.911968  ┆ … ┆ -207.05060 ┆ 62.911968  ┆ -58.48426 ┆ 64.71213  │
│ 21:48:15   ┆     ┆ 9          ┆            ┆   ┆ 9          ┆            ┆ 2         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E29 ┆ -79.237716 ┆ 76.286098  ┆ … ┆ -79.237716 ┆ 76.286098  ┆ -34.8526  ┆ 144.18803 │
│ 22:32:15   ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E15 ┆ -142.23814 ┆ 142.535777 ┆ … ┆ -142.23814 ┆ 142.535777 ┆ -61.94263 ┆ 173.30405 │
│ 23:10:30   ┆     ┆            ┆            ┆   ┆            ┆            ┆ 3         ┆ 3         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [15]:
df_arcs.filter(
    pl.col('is_cycle_slip')
)

shape: (40, 13)
┌────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ epoch      ┆ sv  ┆ gflc_phase ┆ gflc_code  ┆ … ┆ gflc_phase ┆ gflc_code_ ┆ mw_fix    ┆ gflc_leve │
│ ---        ┆ --- ┆ ---        ┆ ---        ┆   ┆ _fix       ┆ fix        ┆ ---       ┆ lled      │
│ datetime[μ ┆ str ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ f64       ┆ ---       │
│ s, UTC]    ┆     ┆            ┆            ┆   ┆ f64        ┆ f64        ┆           ┆ f64       │
╞════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2025-11-28 ┆ G07 ┆ -89.974497 ┆ 144.365291 ┆ … ┆ -6.783127  ┆ 147.924931 ┆ -19.29113 ┆ 145.97529 │
│ 00:34:45   ┆     ┆            ┆            ┆   ┆            ┆            ┆ 3         ┆ 3         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G07 ┆ -29.991348 ┆ 138.711745 ┆ … ┆ -1.011809  ┆ 149.54295  ┆ -18.97371 ┆ 151.74661 │
│ 00:37:30   ┆     ┆            ┆            ┆   ┆            ┆            ┆ 9         ┆ 1         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G30 ┆ -151.50776 ┆ 167.008028 ┆ … ┆ -54.498357 ┆ 122.226996 ┆ -28.72477 ┆ 145.77729 │
│ 01:39:30   ┆     ┆ 4          ┆            ┆   ┆            ┆            ┆ 7         ┆ 2         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G25 ┆ -107.84330 ┆ 119.866593 ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ 02:34:00   ┆     ┆ 2          ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ G17 ┆ -1238.0705 ┆ 63.502454  ┆ … ┆ -251.03068 ┆ 101.897073 ┆ 7.013141  ┆ 76.06983  │
│ 03:15:15   ┆     ┆ 2          ┆            ┆   ┆            ┆            ┆           ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2025-11-28 ┆ E19 ┆ -223.47513 ┆ 157.182894 ┆ … ┆ 169.016313 ┆ 130.651974 ┆ 46.421855 ┆ 136.83909 │
│ 01:39:30   ┆     ┆ 2          ┆            ┆   ┆            ┆            ┆           ┆ 8         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E13 ┆ 265.106122 ┆ 59.550971  ┆ … ┆ -282.66952 ┆ 42.536408  ┆ -69.11120 ┆ 40.880086 │
│ 02:34:30   ┆     ┆            ┆            ┆   ┆ 6          ┆            ┆ 3         ┆           │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E34 ┆ -502.42704 ┆ 180.896165 ┆ … ┆ 100.216057 ┆ 121.896305 ┆ -13.81476 ┆ 177.54336 │
│ 17:55:00   ┆     ┆ 8          ┆            ┆   ┆            ┆            ┆ 5         ┆ 7         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E03 ┆ 521.500646 ┆ 213.823071 ┆ … ┆ 124.501635 ┆ 165.04592  ┆ -15.22278 ┆ 183.28676 │
│ 22:53:00   ┆     ┆            ┆            ┆   ┆            ┆            ┆ 6         ┆ 6         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 2025-11-28 ┆ E03 ┆ -322.45773 ┆ 251.570251 ┆ … ┆ 155.451126 ┆ 178.109565 ┆ -14.34649 ┆ 214.23625 │
│ 22:59:45   ┆     ┆ 5          ┆            ┆   ┆            ┆            ┆ 3         ┆ 8         │
│ UTC        ┆     ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [16]:
df_arcs.filter(
    pl.col('id_arc_valid').is_null()
)

shape: (2_002, 13)
┌─────────────┬─────┬────────────┬───────────┬───┬─────────────┬─────────────┬────────┬────────────┐
│ epoch       ┆ sv  ┆ gflc_phase ┆ gflc_code ┆ … ┆ gflc_phase_ ┆ gflc_code_f ┆ mw_fix ┆ gflc_level │
│ ---         ┆ --- ┆ ---        ┆ ---       ┆   ┆ fix         ┆ ix          ┆ ---    ┆ led        │
│ datetime[μs ┆ str ┆ f64        ┆ f64       ┆   ┆ ---         ┆ ---         ┆ f64    ┆ ---        │
│ , UTC]      ┆     ┆            ┆           ┆   ┆ f64         ┆ f64         ┆        ┆ f64        │
╞═════════════╪═════╪════════════╪═══════════╪═══╪═════════════╪═════════════╪════════╪════════════╡
│ 2025-11-28  ┆ G11 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 00:15:15    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ G11 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 00:15:30    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ G11 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 00:15:45    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ G11 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 00:16:00    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ G11 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 00:16:15    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ …           ┆ …   ┆ …          ┆ …         ┆ … ┆ …           ┆ …           ┆ …      ┆ …          │
│ 2025-11-28  ┆ E06 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 15:30:00    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ E06 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 15:30:15    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ E06 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 15:30:30    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ E06 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 15:30:45    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ 2025-11-28  ┆ E06 ┆ null       ┆ null      ┆ … ┆ null        ┆ null        ┆ null   ┆ null       │
│ 15:31:00    ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
│ UTC         ┆     ┆            ┆           ┆   ┆             ┆             ┆        ┆            │
└─────────────┴─────┴────────────┴───────────┴───┴─────────────┴─────────────┴────────┴────────────┘

In [17]:
# Compute satellites' ECEF coordinates
df_coords = satellite_coordinates(
    sv_ids=df_arcs["sv"],
    epochs=df_arcs["epoch"],
    ephem_dict=ephem_dict
)

df_coords

RuntimeWarning: [GALILEO] E02, E03, E04, E05, E06... (+ 21 more) have no valid ephemerides. Coordinates set to NaN.
ℹ️  These may be missing from NAV file or have been excluded due to invalid/incomplete parameters.

shape: (82_792, 5)
┌─────┬─────────────────────────┬───────────────┬───────────┬───────────────┐
│ sv  ┆ epoch                   ┆ sat_x         ┆ sat_y     ┆ sat_z         │
│ --- ┆ ---                     ┆ ---           ┆ ---       ┆ ---           │
│ str ┆ datetime[μs, UTC]       ┆ f64           ┆ f64       ┆ f64           │
╞═════╪═════════════════════════╪═══════════════╪═══════════╪═══════════════╡
│ G19 ┆ 2025-11-28 00:00:00 UTC ┆ -1.4480e7     ┆ -1.9940e7 ┆ 1.0463e7      │
│ G01 ┆ 2025-11-28 00:00:00 UTC ┆ 1.4128e7      ┆ -1.3009e7 ┆ 1.8327e7      │
│ G13 ┆ 2025-11-28 00:00:00 UTC ┆ -2.2396e7     ┆ -1.3092e7 ┆ 6.0228e6      │
│ G17 ┆ 2025-11-28 00:00:00 UTC ┆ -7.8323e6     ┆ -1.9376e7 ┆ 1.6631e7      │
│ G22 ┆ 2025-11-28 00:00:00 UTC ┆ -4.1329e6     ┆ -1.4993e7 ┆ 2.1891e7      │
│ …   ┆ …                       ┆ …             ┆ …         ┆ …             │
│ G07 ┆ 2025-11-28 23:59:45 UTC ┆ 5.8548e6      ┆ -2.4128e7 ┆ -8.2386e6     │
│ G06 ┆ 2025-11-28 23:59:45 UTC ┆ -5.2602e6     ┆ -2.4393e7 ┆ -8.8174e6     │
│ G01 ┆ 2025-11-28 23:59:45 UTC ┆ 1.4119e7      ┆ -1.2462e7 ┆ 1.8711e7      │
│ G30 ┆ 2025-11-28 23:59:45 UTC ┆ -480267.39419 ┆ -2.6410e7 ┆ 330272.985289 │
│ G17 ┆ 2025-11-28 23:59:45 UTC ┆ -7.4299e6     ┆ -1.9149e7 ┆ 1.7089e7      │
└─────┴─────────────────────────┴───────────────┴───────────┴───────────────┘

In [18]:
# Join coordinates with the observation data
df_geom = df_arcs.join(df_coords, on=["sv", "epoch"], how="left")
df_geom

shape: (82_792, 16)
┌─────────────┬─────┬─────────────┬────────────┬───┬────────────┬───────────┬───────────┬──────────┐
│ epoch       ┆ sv  ┆ gflc_phase  ┆ gflc_code  ┆ … ┆ gflc_level ┆ sat_x     ┆ sat_y     ┆ sat_z    │
│ ---         ┆ --- ┆ ---         ┆ ---        ┆   ┆ led        ┆ ---       ┆ ---       ┆ ---      │
│ datetime[μs ┆ str ┆ f64         ┆ f64        ┆   ┆ ---        ┆ f64       ┆ f64       ┆ f64      │
│ , UTC]      ┆     ┆             ┆            ┆   ┆ f64        ┆           ┆           ┆          │
╞═════════════╪═════╪═════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪══════════╡
│ 2025-11-28  ┆ G19 ┆ -238.459119 ┆ 63.654738  ┆ … ┆ 55.671883  ┆ -1.4480e7 ┆ -1.9940e7 ┆ 1.0463e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G01 ┆ -120.327384 ┆ 103.286665 ┆ … ┆ 103.441579 ┆ 1.4128e7  ┆ -1.3009e7 ┆ 1.8327e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G13 ┆ -153.094106 ┆ 89.485922  ┆ … ┆ 71.7088    ┆ -2.2396e7 ┆ -1.3092e7 ┆ 6.0228e6 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G17 ┆ -236.224711 ┆ 75.066525  ┆ … ┆ 90.875799  ┆ -7.8323e6 ┆ -1.9376e7 ┆ 1.6631e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G22 ┆ -173.034919 ┆ 76.475153  ┆ … ┆ 104.269185 ┆ -4.1329e6 ┆ -1.4993e7 ┆ 2.1891e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ …           ┆ …   ┆ …           ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …        │
│ 2025-11-28  ┆ E02 ┆ -199.732747 ┆ 62.640294  ┆ … ┆ 60.979762  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E27 ┆ -207.027554 ┆ 56.547031  ┆ … ┆ 52.090205  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E07 ┆ -156.208125 ┆ 66.645547  ┆ … ┆ 64.003821  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E08 ┆ -61.879511  ┆ 74.951014  ┆ … ┆ 78.649512  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E30 ┆ -220.762606 ┆ 46.751238  ┆ … ┆ 51.000133  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
└─────────────┴─────┴─────────────┴────────────┴───┴────────────┴───────────┴───────────┴──────────┘

In [19]:
df_geom

shape: (82_792, 16)
┌─────────────┬─────┬─────────────┬────────────┬───┬────────────┬───────────┬───────────┬──────────┐
│ epoch       ┆ sv  ┆ gflc_phase  ┆ gflc_code  ┆ … ┆ gflc_level ┆ sat_x     ┆ sat_y     ┆ sat_z    │
│ ---         ┆ --- ┆ ---         ┆ ---        ┆   ┆ led        ┆ ---       ┆ ---       ┆ ---      │
│ datetime[μs ┆ str ┆ f64         ┆ f64        ┆   ┆ ---        ┆ f64       ┆ f64       ┆ f64      │
│ , UTC]      ┆     ┆             ┆            ┆   ┆ f64        ┆           ┆           ┆          │
╞═════════════╪═════╪═════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪══════════╡
│ 2025-11-28  ┆ G19 ┆ -238.459119 ┆ 63.654738  ┆ … ┆ 55.671883  ┆ -1.4480e7 ┆ -1.9940e7 ┆ 1.0463e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G01 ┆ -120.327384 ┆ 103.286665 ┆ … ┆ 103.441579 ┆ 1.4128e7  ┆ -1.3009e7 ┆ 1.8327e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G13 ┆ -153.094106 ┆ 89.485922  ┆ … ┆ 71.7088    ┆ -2.2396e7 ┆ -1.3092e7 ┆ 6.0228e6 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G17 ┆ -236.224711 ┆ 75.066525  ┆ … ┆ 90.875799  ┆ -7.8323e6 ┆ -1.9376e7 ┆ 1.6631e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ G22 ┆ -173.034919 ┆ 76.475153  ┆ … ┆ 104.269185 ┆ -4.1329e6 ┆ -1.4993e7 ┆ 2.1891e7 │
│ 00:00:00    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ …           ┆ …   ┆ …           ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …        │
│ 2025-11-28  ┆ E02 ┆ -199.732747 ┆ 62.640294  ┆ … ┆ 60.979762  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E27 ┆ -207.027554 ┆ 56.547031  ┆ … ┆ 52.090205  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E07 ┆ -156.208125 ┆ 66.645547  ┆ … ┆ 64.003821  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E08 ┆ -61.879511  ┆ 74.951014  ┆ … ┆ 78.649512  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ 2025-11-28  ┆ E30 ┆ -220.762606 ┆ 46.751238  ┆ … ┆ 51.000133  ┆ NaN       ┆ NaN       ┆ NaN      │
│ 23:59:30    ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
│ UTC         ┆     ┆             ┆            ┆   ┆            ┆           ┆           ┆          │
└─────────────┴─────┴─────────────┴────────────┴───┴────────────┴───────────┴───────────┴──────────┘

In [20]:
df_final = calculate_ipp(df_geom, ctx=ctx, min_elevation=20)
df_final

shape: (65_998, 20)
┌─────────────┬─────┬────────────┬───────────┬───┬───────────┬────────────┬────────────┬───────────┐
│ epoch       ┆ sv  ┆ gflc_phase ┆ gflc_code ┆ … ┆ lat_ipp   ┆ lon_ipp    ┆ azi        ┆ ele       │
│ ---         ┆ --- ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---       │
│ datetime[μs ┆ str ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64        ┆ f64        ┆ f64       │
│ , UTC]      ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
╞═════════════╪═════╪════════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪═══════════╡
│ 2025-11-28  ┆ G19 ┆ -238.45911 ┆ 63.654738 ┆ … ┆ 28.595508 ┆ -114.45142 ┆ 244.914092 ┆ 73.470416 │
│ 00:00:00    ┆     ┆ 9          ┆           ┆   ┆           ┆ 8          ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ G13 ┆ -153.09410 ┆ 89.485922 ┆ … ┆ 27.985744 ┆ -116.89842 ┆ 252.377501 ┆ 42.810822 │
│ 00:00:00    ┆     ┆ 6          ┆           ┆   ┆           ┆ 9          ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ G17 ┆ -236.22471 ┆ 75.066525 ┆ … ┆ 29.634616 ┆ -113.45159 ┆ 7.184559   ┆ 77.340856 │
│ 00:00:00    ┆     ┆ 1          ┆           ┆   ┆           ┆ 2          ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ G22 ┆ -173.03491 ┆ 76.475153 ┆ … ┆ 30.921207 ┆ -113.12221 ┆ 10.643537  ┆ 56.047317 │
│ 00:00:00    ┆     ┆ 9          ┆           ┆   ┆           ┆ 3          ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ G14 ┆ -236.21610 ┆ 79.492281 ┆ … ┆ 30.745411 ┆ -111.81200 ┆ 40.024408  ┆ 51.535215 │
│ 00:00:00    ┆     ┆ 8          ┆           ┆   ┆           ┆ 3          ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ …           ┆ …   ┆ …          ┆ …         ┆ … ┆ …         ┆ …          ┆ …          ┆ …         │
│ 2025-11-28  ┆ E02 ┆ -199.73274 ┆ 62.640294 ┆ … ┆ NaN       ┆ NaN        ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 7          ┆           ┆   ┆           ┆            ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ E27 ┆ -207.02755 ┆ 56.547031 ┆ … ┆ NaN       ┆ NaN        ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 4          ┆           ┆   ┆           ┆            ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ E07 ┆ -156.20812 ┆ 66.645547 ┆ … ┆ NaN       ┆ NaN        ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 5          ┆           ┆   ┆           ┆            ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ E08 ┆ -61.879511 ┆ 74.951014 ┆ … ┆ NaN       ┆ NaN        ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
│ 2025-11-28  ┆ E30 ┆ -220.76260 ┆ 46.751238 ┆ … ┆ NaN       ┆ NaN        ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 6          ┆           ┆   ┆           ┆            ┆            ┆           │
│ UTC         ┆     ┆            ┆           ┆   ┆           ┆            ┆            ┆           │
└─────────────┴─────┴────────────┴───────────┴───┴───────────┴────────────┴────────────┴───────────┘

In [21]:
df_final.filter(
    pl.col("id_arc_valid").is_not_null()
).select(
    [
        "epoch",
        "sv",
        "id_arc_valid",
        "gflc_levelled",
        "lat_ipp",
        "lon_ipp",
        "azi",
        "ele",
    ]
)

shape: (65_349, 8)
┌─────────────┬─────┬─────────────┬─────────────┬───────────┬─────────────┬────────────┬───────────┐
│ epoch       ┆ sv  ┆ id_arc_vali ┆ gflc_levell ┆ lat_ipp   ┆ lon_ipp     ┆ azi        ┆ ele       │
│ ---         ┆ --- ┆ d           ┆ ed          ┆ ---       ┆ ---         ┆ ---        ┆ ---       │
│ datetime[μs ┆ str ┆ ---         ┆ ---         ┆ f64       ┆ f64         ┆ f64        ┆ f64       │
│ , UTC]      ┆     ┆ str         ┆ f64         ┆           ┆             ┆            ┆           │
╞═════════════╪═════╪═════════════╪═════════════╪═══════════╪═════════════╪════════════╪═══════════╡
│ 2025-11-28  ┆ G19 ┆ bdla_g19_20 ┆ 55.671883   ┆ 28.595508 ┆ -114.451428 ┆ 244.914092 ┆ 73.470416 │
│ 00:00:00    ┆     ┆ 251128_001  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ G13 ┆ bdla_g13_20 ┆ 71.7088     ┆ 27.985744 ┆ -116.898429 ┆ 252.377501 ┆ 42.810822 │
│ 00:00:00    ┆     ┆ 251128_001  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ G17 ┆ bdla_g17_20 ┆ 90.875799   ┆ 29.634616 ┆ -113.451592 ┆ 7.184559   ┆ 77.340856 │
│ 00:00:00    ┆     ┆ 251128_001  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ G22 ┆ bdla_g22_20 ┆ 104.269185  ┆ 30.921207 ┆ -113.122213 ┆ 10.643537  ┆ 56.047317 │
│ 00:00:00    ┆     ┆ 251128_001  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ G14 ┆ bdla_g14_20 ┆ 60.016566   ┆ 30.745411 ┆ -111.812003 ┆ 40.024408  ┆ 51.535215 │
│ 00:00:00    ┆     ┆ 251128_001  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ …           ┆ …   ┆ …           ┆ …           ┆ …         ┆ …           ┆ …          ┆ …         │
│ 2025-11-28  ┆ E02 ┆ bdla_e02_20 ┆ 60.979762   ┆ NaN       ┆ NaN         ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 251128_003  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ E27 ┆ bdla_e27_20 ┆ 52.090205   ┆ NaN       ┆ NaN         ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 251128_011  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ E07 ┆ bdla_e07_20 ┆ 64.003821   ┆ NaN       ┆ NaN         ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 251128_003  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ E08 ┆ bdla_e08_20 ┆ 78.649512   ┆ NaN       ┆ NaN         ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 251128_003  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
│ 2025-11-28  ┆ E30 ┆ bdla_e30_20 ┆ 51.000133   ┆ NaN       ┆ NaN         ┆ NaN        ┆ NaN       │
│ 23:59:30    ┆     ┆ 251128_003  ┆             ┆           ┆             ┆            ┆           │
│ UTC         ┆     ┆             ┆             ┆           ┆             ┆            ┆           │
└─────────────┴─────┴─────────────┴─────────────┴───────────┴─────────────┴────────────┴───────────┘

In [31]:
from pytecgg.tec_calibration import calculate_tec

df_calibrated = calculate_tec(
    df_final,
    ctx=ctx,
    max_polynomial_degree=3,
    batch_size_epochs=30
)
df_calibrated = df_calibrated.sort(by='epoch')
df_calibrated

shape: (65_998, 23)
┌─────────────┬─────┬────────────┬────────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ epoch       ┆ sv  ┆ gflc_phase ┆ gflc_code  ┆ … ┆ ele       ┆ bias       ┆ stec      ┆ vtec      │
│ ---         ┆ --- ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---        ┆ ---       ┆ ---       │
│ datetime[μs ┆ str ┆ f64        ┆ f64        ┆   ┆ f64       ┆ f64        ┆ f64       ┆ f64       │
│ , UTC]      ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
╞═════════════╪═════╪════════════╪════════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2025-11-28  ┆ G19 ┆ -238.45911 ┆ 63.654738  ┆ … ┆ 73.470416 ┆ 29.112002  ┆ 26.559882 ┆ 25.575731 │
│ 00:00:00    ┆     ┆ 9          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G13 ┆ -153.09410 ┆ 89.485922  ┆ … ┆ 42.810822 ┆ 27.44149   ┆ 44.26731  ┆ 31.811553 │
│ 00:00:00    ┆     ┆ 6          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G17 ┆ -236.22471 ┆ 75.066525  ┆ … ┆ 77.340856 ┆ 69.025228  ┆ 21.850571 ┆ 21.373889 │
│ 00:00:00    ┆     ┆ 1          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G22 ┆ -173.03491 ┆ 76.475153  ┆ … ┆ 56.047317 ┆ 81.966633  ┆ 22.302552 ┆ 18.920543 │
│ 00:00:00    ┆     ┆ 9          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G14 ┆ -236.21610 ┆ 79.492281  ┆ … ┆ 51.535215 ┆ 39.756707  ┆ 20.259859 ┆ 16.363192 │
│ 00:00:00    ┆     ┆ 8          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ …           ┆ …   ┆ …          ┆ …          ┆ … ┆ …         ┆ …          ┆ …         ┆ …         │
│ 2025-11-28  ┆ G22 ┆ -382.80105 ┆ 63.873647  ┆ … ┆ 55.84887  ┆ 125.747643 ┆ 30.02998  ┆ 25.425005 │
│ 23:59:45    ┆     ┆ 6          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G14 ┆ -190.92419 ┆ 76.475153  ┆ … ┆ 50.916632 ┆ 148.684757 ┆ 30.308363 ┆ 24.300637 │
│ 23:59:45    ┆     ┆ 1          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G06 ┆ -717.11692 ┆ 127.747293 ┆ … ┆ 28.090212 ┆ 102.779151 ┆ 59.883499 ┆ 32.835571 │
│ 23:59:45    ┆     ┆ 4          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G30 ┆ -106.13292 ┆ 102.391997 ┆ … ┆ 44.648705 ┆ 97.98405   ┆ 39.178123 ┆ 28.928487 │
│ 23:59:45    ┆     ┆ 6          ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ 2025-11-28  ┆ G17 ┆ -72.428834 ┆ 70.602699  ┆ … ┆ 75.605006 ┆ 143.079122 ┆ 26.482493 ┆ 25.736635 │
│ 23:59:45    ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
│ UTC         ┆     ┆            ┆            ┆   ┆           ┆            ┆           ┆           │
└─────────────┴─────┴────────────┴────────────┴───┴───────────┴────────────┴───────────┴───────────┘

In [34]:
df_calibrated[['epoch', 'stec']]

shape: (65_998, 2)
┌─────────────────────────┬───────────┐
│ epoch                   ┆ stec      │
│ ---                     ┆ ---       │
│ datetime[μs, UTC]       ┆ f64       │
╞═════════════════════════╪═══════════╡
│ 2025-11-28 00:00:00 UTC ┆ 26.559882 │
│ 2025-11-28 00:00:00 UTC ┆ 44.26731  │
│ 2025-11-28 00:00:00 UTC ┆ 21.850571 │
│ 2025-11-28 00:00:00 UTC ┆ 22.302552 │
│ 2025-11-28 00:00:00 UTC ┆ 20.259859 │
│ …                       ┆ …         │
│ 2025-11-28 23:59:45 UTC ┆ 30.02998  │
│ 2025-11-28 23:59:45 UTC ┆ 30.308363 │
│ 2025-11-28 23:59:45 UTC ┆ 59.883499 │
│ 2025-11-28 23:59:45 UTC ┆ 39.178123 │
│ 2025-11-28 23:59:45 UTC ┆ 26.482493 │
└─────────────────────────┴───────────┘

In [25]:
df_calibrated['sv'].unique()

shape: (58,)
Series: 'sv' [str]
[
	"G13"
	"E26"
	"E10"
	"G19"
	"E29"
	…
	"G21"
	"G22"
	"G01"
	"E34"
	"G17"
]

In [42]:
fig = px.scatter(df_calibrated['epoch', 'stec', 'id_arc_valid'], x='epoch', y='stec', render_mode='svg', color='id_arc_valid')
fig.show()

In [43]:
fig = px.scatter(df_calibrated['epoch', 'vtec', 'id_arc_valid'], x='epoch', y='vtec', render_mode='svg', color='id_arc_valid')
fig.show()